# Generated by Django 3.2.25 on 2025-02-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='blog/blog_default.jpg', upload_to='blog'),
        ),
    ]
